CREATE TABLE IF NOT EXISTS Users (
    userId INTEGER primary key,
    email varchar(64),
    login varchar(64) not null,
    name varchar(255),
    birthday date
);
CREATE TABLE IF NOT EXISTS RatingMPA(
    ratingMPAId INTEGER generated by default as identity primary key,
    name varchar(64)
);
CREATE TABLE IF NOT EXISTS Films (
    filmId INTEGER primary key,
    name varchar(128) not null,
    description varchar(255) not null,
    releaseDate date,
    duration INTEGER,
    ratingMPAId INTEGER,
    CONSTRAINT fk_ratingMPA
              FOREIGN KEY(ratingMPAId)
              REFERENCES RatingMPA(ratingMPAId)
);
CREATE TABLE IF NOT EXISTS Likes(
    filmId INTEGER not null,
    userId INTEGER not null,
    CONSTRAINT fk_film
          FOREIGN KEY(filmId)
          REFERENCES Films(filmId),
    CONSTRAINT fk_user
              FOREIGN KEY(userId)
              REFERENCES Users(userId)
);
CREATE TABLE IF NOT EXISTS Genres(
    genreId INTEGER generated by default as identity primary key,
    name varchar(64)
);
CREATE TABLE IF NOT EXISTS FilmGenre(
    filmId INTEGER NOT NULL,
    genreId INTEGER NOT NULL,
    CONSTRAINT fk_filmId
        FOREIGN KEY(filmId)
        REFERENCES Films(filmId),
    CONSTRAINT fk_genreId
        FOREIGN KEY(genreId)
        REFERENCES Genres(genreId)
);
CREATE TABLE IF NOT EXISTS Friends(
    userId INTEGER not null,
    friendId INTEGER not null,
    status boolean DEFAULT FALSE,
    CONSTRAINT fk_userId
         FOREIGN KEY(userId)
         REFERENCES Users(userId),
    CONSTRAINT fk_friend
         FOREIGN KEY(friendId)
         REFERENCES Users(userId)
);
